### ISSUE TITLE
"View" cannot be modified if the view is set as a default view for one or more users

### ISSUE THREAD

**Issue by prabha11-sys** [skyscrapr/terraform-provider-cloudability#28]
Hi @skyscrapr ,
I was trying to update a view through terraform and I received the below error. This view which I am trying to modify is set as the default view for one ore more users. If I perform the modification on the "Views" GUI console, I am able to perform this change successfully,

Below is the output from terraform apply

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudability_view.AWS_DEV: Destroying... [id=346603]
cloudability_view.AWS_Platform: Creating...

╷
│ Error: {"error":{"status":422,"code":"unprocessable_entity","messages":["View is being used as a default by one or more users."],"uniqueid":"55a007ea-21e6-11ee-a291-06863542dc67","typeid":"cc6569e548073a361be6b0dead8e805e","traceid":"557d691d-21e6-11ee-a291-06863542dc67"}}

**Comment by skyscrapr** [comment]
Is terraform trying to update the view of destroy and create?

Can you give me an example config to test?

**Comment by prabha11-sys** [comment]
I was trying to update the config,

FROM,

resource "cloudability_view" "AWS_DEV" {
  owner_id                 = "240740"
  shared_with_organization = false
  shared_with_users        = ["240742", "262108", "263641", "272551", "273471", "273472", "273473", "273474", "273475", "273476", "276462"]
  title                    = "AWS_DEV"
  filter {
    comparator = "=="
    field      = "category5"
    value      = "AWS_DEV"
  }
}


TO,

resource "cloudability_view" "AWS_Platform" {
  owner_id                 = "240740"
  shared_with_organization = false
  shared_with_users        = ["240742", "262108", "263641", "272551", "273471", "273472", "273473", "273474", "273475", "273476", "276462"]
  title                    = "AWS_DEV"
  filter {
    comparator = "=="
    field      = "category5"
    value      = "AWS_Platform"
  }

**Comment by skyscrapr** [comment]
OK, i just realised why you are seeing this issue.
By renaming the resource, you are actually triggering a delete of the removed resource and creation of the new resource.
This is preventing the deletion due to users having the view set as a default view.

There are a number of ways to resolve this:

1. Do not change the resource name:

FROM

resource "cloudability_view" "AWS_DEV" {
owner_id = "240740"
shared_with_organization = false
shared_with_users = ["240742", "262108", "263641", "272551", "273471", "273472", "273473", "273474", "273475", "273476", "276462"]
title = "AWS_DEV"
filter {
comparator = "=="
field = "category5"
value = "AWS_DEV"
}
}

TO,

resource "cloudability_view" "AWS_DEV" {
owner_id = "240740"
shared_with_organization = false
shared_with_users = ["240742", "262108", "263641", "272551", "273471", "273472", "273473", "273474", "273475", "273476", "276462"]
title = "AWS_DEV"
filter {
comparator = "=="
field = "category5"
value = "AWS_Platform"
}

If you really need to change the resource name, you will need to change the name in state using this [method](https://developer.hashicorp.com/terraform/cli/commands/state/mv)

You should be able to rename the resource and then update the filter. 

I hope that makes sense

**Comment by skyscrapr** [comment]
I don't think this is an issue with the provider. So I'm closing the issue. 

Please reopen if needed.
